workflow:
  id: ProductDocumentation
  inputs:
    events:
      cloud_events:
        - type: input_message_received
          data_schema: 
            type: string
  nodes:
    - id: GetProductInfoStep
      type: dotnet
      description: Gather information about the product
      agent:
        type: Steps.GetProductInfoStep, ProductDocumentation
      on_complete:
        - on_condition:
            type: default
            emits:
              - event_type: GetProductInfo.OnResult
    - id: GenerateDocumentationStep
      type: dotnet
      description: Generate documentation for the product with LLM
      agent:
        type: Steps.GenerateDocumentationStep, ProductDocumentation
      on_complete:
        - on_condition:
            type: default
            emits:
              - event_type: GenerateDocumentation.OnResult
    - id: PublishDocumentationStep
      type: dotnet
      description: Publish the documentation
      agent:
        type: Steps.PublishDocumentationStep, ProductDocumentation
      on_complete:
        - on_condition:
            type: default
            emits:
              - event_type: ProcessCompleted
  orchestration:
    - listen_for:
        event: input_message_received
        from: _workflow_
      then:
        - node: GetProductInfoStep
    - listen_for:
        event: GetProductInfo.OnResult
        from: GetProductInfoStep
      then:
        - node: GenerateDocumentationStep
    - listen_for:
        event: GenerateDocumentation.OnResult
        from: GenerateDocumentationStep
      then:
        - node: PublishDocumentationStep
